# Project information
site_name: 'IoTaaP Core Library'
site_description: 'IoTaaP Core Library Documentation'
repo_url: 'https://github.com/iotaap/docs-core'
nav:
  - Home: index.md
  - IoTaaP: iotaap-class.md
  - ADC: adc.md
  - Buzzer: buzzer.md
<<<<<<< HEAD
=======
  - DAC: dac.md
  - Hall: hall.md
  - Misc: misc.md
  - MQTT: mqtt.md
  - OLED: oled.md
  - PWM: pwm.md
  - Serial: serial.md
  - TCP: tcp.md
  - WiFi: wifi.md
>>>>>>> 526696c60648c5ed12c9315297394636d9004cf7
          
# Copyright
copyright: 'Copyright IoTaaP'

theme: 
    name: material
    palette:
        primary: 'light-blue'
        accent: 'deep-purple'
#    font:
#        text: 'Ubuntu'
#        code: 'Ubuntu Mono'
    logo: 'images/logo.png'
    favicon: 'images/favicon.png'
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  social:
    - type: 'github'
      link: 'https://github.com/iotaap'
    - type: 'twitter'
      link: 'https://twitter.com/iotaap'
    - type: 'facebook'
      link: 'https://www.facebook.com/iotaap'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCC9hU3ndh6bh-LbW3YjI98g'