# Project information
site_name: 'IoTaaP Core Library'
site_description: 'IoTaaP Core Library Documentation'
repo_url: 'https://github.com/iotaap/docs-core'
nav:
  - Home: index.md
  - IoTaaP: iotaap-class.md
  - ADC: adc.md
  - Buzzer: buzzer.md
  - DAC: dac.md
  - Hall: hall.md
  - Misc: misc.md
  - MQTT: mqtt.md
  - OLED: oled.md
  - PWM: pwm.md
  - Serial: serial.md
  - TCP: tcp.md
  - WiFi: wifi.md
          
copyright: 'Copyright &copy; IoTaaP'

theme: 
    name: material
    palette:
        primary: 'light-blue'
        accent: 'deep-purple'
    logo: 'images/logo.png'
    favicon: 'images/favicon.png'

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iotaap
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iotaap
      name: Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/iotaap
      name: Facebook
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCC9hU3ndh6bh-LbW3YjI98g
      name: YouTube